version: "3.8"
services:
  postgres:
    image: postgres:10-alpine3.16
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=location-api

  location-service-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/location-api?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock